version: '3.8'

services:
  # Serviço do Backend (Node.js API)
  backend:
    build: ./backend
    container_name: estoque_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT_HOST}:${BACKEND_PORT_CONTAINER}"
    environment:
      # ADICIONADO: Define o fuso horário para o container do backend
      - TZ=America/Sao_Paulo
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT_CONTAINER}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - db-data:/app/database
    networks:
      - estoque-net

  # Serviço do Frontend (Vue.js + Nginx)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=${API_URL_FOR_FRONTEND}
    container_name: estoque_frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT_HOST}:80"
    # ADICIONADO: Define o fuso horário também para o container do Nginx
    # Isso garante que os logs de acesso do servidor web fiquem no horário correto.
    environment:
      - TZ=America/Sao_Paulo
    depends_on:
      - backend
    networks:
      - estoque-net

# Define os volumes nomeados
volumes:
  db-data:

# Define a rede customizada para os serviços se comunicarem
networks:
  estoque-net:
    driver: bridge